// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  code: __t.string().primaryKey(),
  status: __t.string(),
  isPublic: __t.bool().name("is_public"),
  playerCount: __t.u32().name("player_count"),
  maxPlayers: __t.u32().name("max_players"),
  rounds: __t.u32(),
  turnSeconds: __t.u32().name("turn_seconds"),
  artist: __t.identity(),
  currentWord: __t.string().name("current_word"),
  turn: __t.u32(),
  round: __t.u32(),
  turnStartedAt: __t.timestamp().name("turn_started_at"),
  createdAt: __t.timestamp().name("created_at"),
});
