// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Drawing = __t.object("Drawing", {
  id: __t.u64(),
  gameCode: __t.string(),
  turn: __t.u32(),
  artist: __t.identity(),
  artistName: __t.string(),
  word: __t.string(),
});
export type Drawing = __Infer<typeof Drawing>;

export const Game = __t.object("Game", {
  code: __t.string(),
  status: __t.string(),
  isPublic: __t.bool(),
  playerCount: __t.u32(),
  maxPlayers: __t.u32(),
  rounds: __t.u32(),
  turnSeconds: __t.u32(),
  artist: __t.identity(),
  currentWord: __t.string(),
  turn: __t.u32(),
  round: __t.u32(),
  turnStartedAt: __t.timestamp(),
  createdAt: __t.timestamp(),
});
export type Game = __Infer<typeof Game>;

export const Guess = __t.object("Guess", {
  id: __t.u64(),
  gameCode: __t.string(),
  player: __t.identity(),
  username: __t.string(),
  text: __t.string(),
  correct: __t.bool(),
  turn: __t.u32(),
  createdAt: __t.timestamp(),
});
export type Guess = __Infer<typeof Guess>;

export const LiveStroke = __t.object("LiveStroke", {
  gameCode: __t.string(),
  points: __t.array(__t.f32()),
  color: __t.string(),
  width: __t.f32(),
  threeD: __t.bool(),
});
export type LiveStroke = __Infer<typeof LiveStroke>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  username: __t.string(),
  gameCode: __t.string(),
  isHost: __t.bool(),
  score: __t.u32(),
  online: __t.bool(),
  joinedAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const Stroke = __t.object("Stroke", {
  id: __t.u64(),
  gameCode: __t.string(),
  turn: __t.u32(),
  points: __t.array(__t.f32()),
  color: __t.string(),
  width: __t.f32(),
  threeD: __t.bool(),
});
export type Stroke = __Infer<typeof Stroke>;

export const Vote = __t.object("Vote", {
  id: __t.u64(),
  gameCode: __t.string(),
  voter: __t.identity(),
  turn: __t.u32(),
  category: __t.string(),
});
export type Vote = __Infer<typeof Vote>;

