// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddStrokeReducer from "../add_stroke_reducer";
import AutoPickWordReducer from "../auto_pick_word_reducer";
import CastVoteReducer from "../cast_vote_reducer";
import ChooseWordReducer from "../choose_word_reducer";
import ClearCanvasReducer from "../clear_canvas_reducer";
import CreateGameReducer from "../create_game_reducer";
import EndTurnReducer from "../end_turn_reducer";
import JoinGameReducer from "../join_game_reducer";
import LeaveGameReducer from "../leave_game_reducer";
import LeaveWatchReducer from "../leave_watch_reducer";
import PlayAgainReducer from "../play_again_reducer";
import StartGameReducer from "../start_game_reducer";
import SubmitGuessReducer from "../submit_guess_reducer";
import UpdateLiveStrokeReducer from "../update_live_stroke_reducer";
import WatchGameReducer from "../watch_game_reducer";

export type AddStrokeParams = __Infer<typeof AddStrokeReducer>;
export type AutoPickWordParams = __Infer<typeof AutoPickWordReducer>;
export type CastVoteParams = __Infer<typeof CastVoteReducer>;
export type ChooseWordParams = __Infer<typeof ChooseWordReducer>;
export type ClearCanvasParams = __Infer<typeof ClearCanvasReducer>;
export type CreateGameParams = __Infer<typeof CreateGameReducer>;
export type EndTurnParams = __Infer<typeof EndTurnReducer>;
export type JoinGameParams = __Infer<typeof JoinGameReducer>;
export type LeaveGameParams = __Infer<typeof LeaveGameReducer>;
export type LeaveWatchParams = __Infer<typeof LeaveWatchReducer>;
export type PlayAgainParams = __Infer<typeof PlayAgainReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;
export type SubmitGuessParams = __Infer<typeof SubmitGuessReducer>;
export type UpdateLiveStrokeParams = __Infer<typeof UpdateLiveStrokeReducer>;
export type WatchGameParams = __Infer<typeof WatchGameReducer>;

